pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Clean venv') {
            steps {
                // Delete venv folder if it exists (Windows)
                bat """
                IF EXIST %VENV_DIR% (
                    rmdir /S /Q %VENV_DIR%
                )
                """
            }
        }

        stage('Set up Python venv') {
            steps {
                // Create venv and upgrade pip
                bat "python -m venv %VENV_DIR%"
                bat "%VENV_DIR%\\Scripts\\python -m pip install --upgrade pip"
            }
        }

        stage('Install dependencies') {
            steps {
                bat "%VENV_DIR%\\Scripts\\pip install -r requirements.txt"
            }
        }

        stage('Run Tests') {
            steps {
                // Generate JUnit XML so the 'junit' step can read it
                bat "%VENV_DIR%\\Scripts\\pytest scripts/ --junitxml=test-results.xml"
            }
        }
    }

    post {
        always {
            // Publish test report generated by pytest
            junit 'test-results.xml'
        }
    }
}
